baseurl = "/"
languageCode = "en-us"
title = "Scillus"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    description = "A minimal example of building Rmd files under the static/ directory of a website based on blogdown and Hugo."
    footer = "&copy; [Mingchu Xu](https://github.com/xmc811) 2019 - 2021 | [Github](https://github.com/xmc811/Scillus) "
